name = "localsearch"
pages_build_output_dir = "./dist"
compatibility_date = "2025-09-11"

# CRITICAL: Always deploy to localsearch.franzai.com
# Never use wrangler deploy directly - always use npm run deploy
# Custom domain configured via Cloudflare Pages dashboard