name = "localsearch"
compatibility_date = "2025-09-11"

# Static assets configuration for Pages
[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Routes - serve from custom domain
[[routes]]
pattern = "localsearch.franzai.com/*"
zone_name = "franzai.com"